[build]
  base = "gestionale-x"
  command = "npm run build"
  publish = "gestionale-x/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200